# ============================================================
# build-base.yml
# Brings the system to a clean, up-to-date baseline.
# ============================================================
- name: Build Base
  hosts: "{{ machine_type }}"
  become: true
  roles:
    - update-system
    - flatpak-packages
    - remove-packages
    - distrobox
    - vmm
    - vm-windows
    - vm-gaming