# ============================================================
# configure.yml
# Configures apps and the terminal environment.
# ============================================================
- name: Configure
  hosts: "{{ machine_type }}"
  become: true
  vars_files:
    - vault.yml
  roles:
    # - 9_github
    # - 10_appearance
    # - 11_power
    # - 12_gnome-settings
    # - 13_touchpad
    # - 14_audio
    # - 15_package-config
    # - 16_custom-terminal
    - 17_custom-commands