# ============================================================
# inventory.ini
# ============================================================
[laptop]
laptop_host ansible_connection=local ansible_host=localhost main_user=erys_laptop

[pc]
pc_host ansible_connection=local ansible_host=localhost main_user=erys_pc

[all:vars]
ansible_user=root
